# Appveyor build configuration for Tau Labs by shred

os: MinGW
install:
  - set QTDIR=C:\Qt\Qt5.4
  - set PATH=%PATH%;%QTDIR%\bin:C:\Qt\Tools\mingw491_32
  - cmd: cinst wget -x86
  - cmd: cinst 7zip.commandline -x86
#  - mingw32-make arm_sdk_install
  - mingw32-make gcs